# Generated by Django 2.2.12 on 2020-12-25 17:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0024_auto_20201225_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='payround1',
            field=otree.db.models.IntegerField(default=2, null=True),
        ),
    ]
