# Generated by Django 2.2.12 on 2020-12-25 18:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0033_auto_20201225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='payround1',
            field=otree.db.models.IntegerField(default=11, null=True),
        ),
    ]
