# Generated by Django 2.2.12 on 2020-12-16 19:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_reputation', '0002_auto_20201216_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tercih_2',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Deneyde kararınızı aşağıdakilerden hangisi açıklar? Birden fazla seçenek işaretleyebilirsiniz. '),
        ),
    ]
