# Generated by Django 2.2.12 on 2020-12-18 18:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0002_auto_20201218_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='payround2',
            field=otree.db.models.IntegerField(default=13, null=True),
        ),
    ]
