# Generated by Django 2.2.12 on 2020-12-17 19:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part3', '0004_auto_20201217_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='payround1',
            field=otree.db.models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='payround2',
            field=otree.db.models.IntegerField(default=11, null=True),
        ),
    ]
